### ISSUE TITLE
Better macros

### ISSUE THREAD

**Issue by mkstoyanov** [dannys4/FFT-Research-F20#4]
https://github.com/dannys4/FFT-Research-F20/blob/a6a45f6c761b5d84122a1cb1261231d6df839328/FFTE/include/algos.hpp#L41

If `constexpr` is the only C++-14 feature that you are using, it is better to  make a macro:
```
#if <using c++-14>
    #define danny_constexp constexpr
#else
    #define danny_constexp 
#endif
....
danny_constexp Fourier_Transform(fft_type fft): type(fft) {}
```

Obviously use something better than `danny_constexpr` as a name.

**Comment by dannys4** [comment]
I'm unclear on what you're suggesting here. Perhaps I'm misinterpreting, but it looks to me like these are identical regardless of whether I'm using c++14 or not. Further, due to its simplicity, the Fourier_Transform class has no issue being used with C++11 (at least, `g++` has no issue compiling this with the `-std=c++11` flag.

**Comment by mkstoyanov** [comment]
Bad code in the comment, just updated now.

The idea is that in c++14 mode you have the macro defined to `constexpt` while otherwise it will be defined as empty. The idea is that you don't have two blocks of code that are identical but for the introduction of `constexpt`.

**Comment by dannys4** [comment]
Understood, and this makes sense. I do something similar [here](https://github.com/dannys4/FFT-Research-F20/blob/c745529ea58b76de80f0950fedea2fc61f5cc5f8/FFTE/include/test.hpp#L15). I will address this in the link above in the future-- it will require some refactoring of code so that there's minimal overlap. However, this specific line is not an issue because C++11 does support `Fourier_Transform` having this `constexpr` constructor and methods.

**Comment by dannys4** [comment]
See [here](https://github.com/dannys4/FFT-Research-F20/issues/8) for related and larger issue.
